services:
  bot:
    build: .
    ports:
      - "3001:3001"
    volumes:
      - ./wwebjs_auth:/app/.wwebjs_auth
      - ./wwebjs_cache:/app/.wwebjs_cache
    restart: unless-stopped
    shm_size: "1gb"